server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  metrics:
    tags:
      application: catalog-service

services:
  stock:
    base-url: http://stock-service:8082

resilience4j:
  metrics:
    enabled: true

  retry:
    retryAspectOrder: 1
    instances:
      stockService:
        maxAttempts: 3
        waitDuration: 500ms
        enableExponentialBackoff: false
        retryExceptions:
          - java.net.ConnectException
          - java.net.UnknownHostException
          - org.springframework.web.reactive.function.client.WebClientRequestException
          - java.util.concurrent.TimeoutException
          - java.lang.RuntimeException
        ignoreExceptions:
          - java.lang.IllegalArgumentException
  circuitbreaker:
    circuitBreakerAspectOrder: 2
    instances:
      stockService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        ignoreExceptions:
          - java.lang.IllegalArgumentException
  timelimiter:
    instances:
      timeout-duration: 2s

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.example.catalog: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} %highlight(%-5level) [%thread] %cyan(%logger{36}) - %msg%n"